{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "77445e3e-9b28-417e-a80f-72e381ea76c3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>amfi_code</th>\n",
       "      <th>stock_symbol</th>\n",
       "      <th>stock_name</th>\n",
       "      <th>sector</th>\n",
       "      <th>weight_pct</th>\n",
       "      <th>market_value_cr</th>\n",
       "      <th>current_price_inr</th>\n",
       "      <th>portfolio_date</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>119551</td>\n",
       "      <td>POWERGRID</td>\n",
       "      <td>Power Grid Corporation</td>\n",
       "      <td>Utilities</td>\n",
       "      <td>13.85</td>\n",
       "      <td>737.09</td>\n",
       "      <td>6011.08</td>\n",
       "      <td>2025-12-31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>119551</td>\n",
       "      <td>HDFCBANK</td>\n",
       "      <td>HDFC Bank Ltd</td>\n",
       "      <td>Banking</td>\n",
       "      <td>11.19</td>\n",
       "      <td>88.97</td>\n",
       "      <td>1074.65</td>\n",
       "      <td>2025-12-31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>119551</td>\n",
       "      <td>GRASIM</td>\n",
       "      <td>Grasim Industries Ltd</td>\n",
       "      <td>Diversified</td>\n",
       "      <td>9.90</td>\n",
       "      <td>208.45</td>\n",
       "      <td>5964.59</td>\n",
       "      <td>2025-12-31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>119551</td>\n",
       "      <td>DRREDDY</td>\n",
       "      <td>Dr. Reddy's Laboratories</td>\n",
       "      <td>Pharma</td>\n",
       "      <td>4.76</td>\n",
       "      <td>161.32</td>\n",
       "      <td>3748.82</td>\n",
       "      <td>2025-12-31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>119551</td>\n",
       "      <td>ASIANPAINT</td>\n",
       "      <td>Asian Paints Ltd</td>\n",
       "      <td>Paints</td>\n",
       "      <td>10.25</td>\n",
       "      <td>725.90</td>\n",
       "      <td>1321.45</td>\n",
       "      <td>2025-12-31</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   amfi_code stock_symbol                stock_name       sector  weight_pct  \\\n",
       "0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85   \n",
       "1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19   \n",
       "2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90   \n",
       "3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76   \n",
       "4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25   \n",
       "\n",
       "   market_value_cr  current_price_inr portfolio_date  \n",
       "0           737.09            6011.08     2025-12-31  \n",
       "1            88.97            1074.65     2025-12-31  \n",
       "2           208.45            5964.59     2025-12-31  \n",
       "3           161.32            3748.82     2025-12-31  \n",
       "4           725.90            1321.45     2025-12-31  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "holdings = pd.read_csv(\n",
    "    \"../data/processed/09_portfolio_holdings.csv\"\n",
    ")\n",
    "\n",
    "holdings.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "dc9e1894-dbd4-420b-a7f0-cd2d0bca0eb3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter Risk Appetite (Low/Moderate/High):  Low\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    amfi_code                                    scheme_name  sharpe_ratio  \\\n",
      "4      101207         ABSL Small Cap Fund - Regular - Growth      0.162661   \n",
      "15     119093           Axis Bluechip Fund - Direct - Growth      0.129614   \n",
      "29     120842  Kotak Emerging Equity Fund - Regular - Growth      0.076000   \n",
      "\n",
      "   risk_grade  \n",
      "4         Low  \n",
      "15        Low  \n",
      "29        Low  \n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "\n",
    "sharpe = pd.read_csv(\"../reports/sharpe_ratio.csv\")\n",
    "\n",
    "sharpe['risk_grade'] = pd.qcut(\n",
    "    sharpe['sharpe_ratio'],\n",
    "    q=3,\n",
    "    labels=['Low', 'Moderate', 'High']\n",
    ")\n",
    "\n",
    "risk = input(\n",
    "    \"Enter Risk Appetite (Low/Moderate/High): \"\n",
    ")\n",
    "\n",
    "recommendations = (\n",
    "    sharpe[\n",
    "        sharpe['risk_grade'] == risk\n",
    "    ]\n",
    "    .sort_values(\n",
    "        'sharpe_ratio',\n",
    "        ascending=False\n",
    "    )\n",
    "    .head(3)\n",
    ")\n",
    "\n",
    "print(recommendations)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "da8bb0c3-6b70-43ef-a11c-2cc8a8e58805",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>amfi_code</th>\n",
       "      <th>stock_symbol</th>\n",
       "      <th>stock_name</th>\n",
       "      <th>sector</th>\n",
       "      <th>weight_pct</th>\n",
       "      <th>market_value_cr</th>\n",
       "      <th>current_price_inr</th>\n",
       "      <th>portfolio_date</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>119551</td>\n",
       "      <td>POWERGRID</td>\n",
       "      <td>Power Grid Corporation</td>\n",
       "      <td>Utilities</td>\n",
       "      <td>13.85</td>\n",
       "      <td>737.09</td>\n",
       "      <td>6011.08</td>\n",
       "      <td>2025-12-31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>119551</td>\n",
       "      <td>HDFCBANK</td>\n",
       "      <td>HDFC Bank Ltd</td>\n",
       "      <td>Banking</td>\n",
       "      <td>11.19</td>\n",
       "      <td>88.97</td>\n",
       "      <td>1074.65</td>\n",
       "      <td>2025-12-31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>119551</td>\n",
       "      <td>GRASIM</td>\n",
       "      <td>Grasim Industries Ltd</td>\n",
       "      <td>Diversified</td>\n",
       "      <td>9.90</td>\n",
       "      <td>208.45</td>\n",
       "      <td>5964.59</td>\n",
       "      <td>2025-12-31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>119551</td>\n",
       "      <td>DRREDDY</td>\n",
       "      <td>Dr. Reddy's Laboratories</td>\n",
       "      <td>Pharma</td>\n",
       "      <td>4.76</td>\n",
       "      <td>161.32</td>\n",
       "      <td>3748.82</td>\n",
       "      <td>2025-12-31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>119551</td>\n",
       "      <td>ASIANPAINT</td>\n",
       "      <td>Asian Paints Ltd</td>\n",
       "      <td>Paints</td>\n",
       "      <td>10.25</td>\n",
       "      <td>725.90</td>\n",
       "      <td>1321.45</td>\n",
       "      <td>2025-12-31</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   amfi_code stock_symbol                stock_name       sector  weight_pct  \\\n",
       "0     119551    POWERGRID    Power Grid Corporation    Utilities       13.85   \n",
       "1     119551     HDFCBANK             HDFC Bank Ltd      Banking       11.19   \n",
       "2     119551       GRASIM     Grasim Industries Ltd  Diversified        9.90   \n",
       "3     119551      DRREDDY  Dr. Reddy's Laboratories       Pharma        4.76   \n",
       "4     119551   ASIANPAINT          Asian Paints Ltd       Paints       10.25   \n",
       "\n",
       "   market_value_cr  current_price_inr portfolio_date  \n",
       "0           737.09            6011.08     2025-12-31  \n",
       "1            88.97            1074.65     2025-12-31  \n",
       "2           208.45            5964.59     2025-12-31  \n",
       "3           161.32            3748.82     2025-12-31  \n",
       "4           725.90            1321.45     2025-12-31  "
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "holdings.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "34e88860-621f-4912-bab1-fdd77b68b8f3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
